# Generated by Django 6.0.2 on 2026-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source_code', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pub_update', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('django', 'Django'), ('sql', 'SQL'), ('java', 'Java'), ('php', 'PHP'), ('kotlin', 'Kotlin'), ('markdown', 'Markdown')], max_length=20)),
                ('cont_visited', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
