# Generated by Django 6.0.2 on 2026-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='latitude',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='longitude',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
