# Generated by Django 6.0.2 on 2026-02-17 12:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_latitude_alter_snippet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=4326),
        ),
    ]
