# Generated by Django 6.0.2 on 2026-02-18 11:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
